spring:
  profiles:
    active: chaos-monkey
chaos:
  monkey:
    enabled: true
    assaults:
      memoryActive: false
      memoryFillIncrementFraction: 0.95
      memoryFillTargetFraction: 0.91
      memoryMillisecondsHoldFilledMemory: 90000
      memoryMillisecondsWaitNextIncrease: 1000
      exceptionsActive: false
      killApplicationActive: false
      runtimeAssaultCronExpression : "* * * * * *"
      latencyActive: false
      latencyRangeStart: 5000
      latencyRangeEnd: 8000
      level: 1
    watcher:
      component: false
      controller: false
      repository: true
      restController: false
      service: false
management:
  endpoint:
    chaosmonkey:
      enabled: true
    chaosmonkeyjmx:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,chaosmonkey
